More advanced sqlite-csv implementation

diff --git a/bin/sqlite-csv b/bin/sqlite-csv
--- a/bin/sqlite-csv
+++ b/bin/sqlite-csv
@@ -1,15 +1,29 @@
-#!/bin/sh
+#!/bin/bash
+
+test -z "$output" && output='column'
+test -z "$headers" && headers='on'
 
 if [ -t 0 ]; then
   # running interactively: read from file
   file=${1:-data.csv}
-  sql=${2:-"select * from db limit 5"}
-  test -f "$file" && sqlite3 :memory: -cmd '.mode csv' -cmd '.import $file db' $sql || echo "File $file not found" 
+  shift
+  sql=${@:-"select * from db limit 5"}
+  test -f "$file" || (echo "File $file not found"; exit 1)
 else
   # running thru pipe: read from stdin
-  test -z "$output" && output='column'
   sql=${@:-"select * from db limit 5"}
-  test -z "$sql" && echo "usage: [output=column|csv|line|] $0 [sqlite-string]" && exit 1
+  echo "$sql"
+fi
+
+test -z "$sql" && echo "usage: [output=column|csv|line|] $0 [file-if-not-piped] [sqlite-string]" && exit 1
+
+sql_pipe() {
   # remove spaces after line start and commas (padding spaces), then pipe to sqlite
-  sed 's/, */,/g' | sed 's/^ *//g' |  sqlite3 :memory: -cmd '.mode csv' -cmd ".import '|cat -' db" -cmd ".mode $output" "$sql"
+  sed 's/, */,/g' | sed 's/^ *//g' |  sqlite3 :memory: -cmd '.mode csv' -cmd ".import '|cat -' db" -cmd ".mode $output" -cmd ".headers $headers" "$sql"
+}
+
+if [ -t 0 ]; then
+  cat "$file" | sql_pipe
+else
+  sql_pipe
 fi
